version: '3'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    container_name: calculadora-template
    environment:
      - CHOKIDAR_USEPOLLING=true  # Habilita o polling para monitorar as mudanças no código
    volumes:
      - ./src:/app/src       # Mapeia o diretório 'src' local para o 'src' dentro do container
