export const field = {
  BACKGROUND_IMAGE: '🖼️ Imagem de Fundo',
  BUTTON: '📝 Botão',
  BUTTON1: '📝 Botão 1',
  BUTTON2: '📝 Botão 2',
  BUTTON3: '📝 Botão 3',
  BUTTON4: '📝 Botão 4',
  COLOR: '⚙️ Cor',
  COUPON: '📝 Cupom',
  COUPON1: '📝 Cupom 1',
  COUPON2: '📝 Cupom 2',
  DISCOUNT_TAG: '📝 Tag Desconto',
  DISCOUNT_TAG1: '📝 Tag Desconto 1',
  DISCOUNT_TAG2: '📝 Tag Desconto 2',
  ICON: '🖼️ Ícone',
  IMAGE: '🖼️ Imagem',
  IMAGE1: '🖼️ Imagem 1',
  IMAGE2: '🖼️ Imagem 2',
  IMAGE3: '🖼️ Imagem 3',
  IMAGE4: '🖼️ Imagem 4',
  IMAGE5: '🖼️ Imagem 5',
  INSTALLMENT: '📝 Parcelamento',
  INSTALLMENT1: '📝 Parcelamento 1',
  INSTALLMENT2: '📝 Parcelamento 2',
  INSTALLMENT3: '📝 Parcelamento 3',
  ITEM_LINK1: '🔗 Link do Item 1',
  ITEM_LINK2: '🔗 Link do Item 2',
  ITEM_LINK3: '🔗 Link do Item 3',
  ITEM_TEXT: '📝 Texto Item',
  ITEM_TEXT1: '📝 Texto Item 1',
  ITEM_TEXT2: '📝 Texto Item 2',
  ITEM_TEXT3: '📝 Texto Item 3',
  ITEM_TEXT4: '📝 Texto Item 4',
  ITEM_TEXT5: '📝 Texto Item 5',
  ITEM_TEXT6: '📝 Texto Item 6',
  ITEM_TEXT7: '📝 Texto Item 7',
  ITEM_TEXT8: '📝 Texto Item 8',
  ITEM_TITLE: '📝 Título Item',
  ITEM_TITLE1: '📝 Título Item 1',
  ITEM_TITLE2: '📝 Título Item 2',
  ITEM_TITLE3: '📝 Título Item 3',
  ITEM_TITLE4: '📝 Título Item 4',
  LABEL: '📝 Label',
  LABEL1: '📝 Label 1',
  LABEL2: '📝 Label 2',
  LABEL3: '📝 Label 3',
  LABEL_TAG: '📝 Tag Label',
  LABEL_TAG1: '📝 Tag Label 1',
  LABEL_TAG2: '📝 Tag Label 2',
  LINK1: '🔗 Link 1',
  LINK2: '🔗 Link 2',
  LINK3: '🔗 Link 3',
  LINK4: '🔗 Link 4',
  LINK5: '🔗 Link 5',
  MODULE_LINK: '🔗 Link do módulo',
  MODULE_TITLE: '📝 Título do módulo',
  NAME: '📝 Nome',
  NAME1: '📝 Nome 1',
  NAME2: '📝 Nome 2',
  NAME3: '📝 Nome 3',
  NAME4: '📝 Nome 4',
  PARAGRAPH_TEXT: '📝 Texto parágrafo',
  PARAGRAPH_TEXT1: '📝 Texto parágrafo 1',
  PARAGRAPH_TEXT2: '📝 Texto parágrafo 2',
  PARAGRAPH_TEXT3: '📝 Texto parágrafo 3',
  PRE_TITLE: '📝 Pré-título',
  PRE_TITLE1: '📝 Pré-título 1',
  PRE_TITLE2: '📝 Pré-título 2',
  PRE_TITLE3: '📝 Pré-título 3',
  PRICE: '📝 Preço',
  PRICE1: '📝 Preço 1',
  PRICE2: '📝 Preço 2',
  PRICE3: '📝 Preço 3',
  PRICE4: '📝 Preço 4',
  PRICE5: '📝 Preço 5',
  PRODUCT_NAME: '📝 Nome do Produto',
  PRODUCT_NAME1: '📝 Nome do Produto 1',
  PRODUCT_NAME2: '📝 Nome do Produto 2',
  PRODUCT_NAME3: '📝 Nome do Produto 3',
  SUBTITLE: '📝 Subtítulo',
  SUPPORT_TEXT: '📝 Texto apoio',
  SUPPORT_TEXT1: '📝 Texto apoio 1',
  SUPPORT_TEXT2: '📝 Texto apoio 2',
  TESTIMONIAL: '📝 Depoimento',
  TEXT_OF: '📝 Texto "de"',
  TEXT_OF1: '📝 Texto "de" 1',
  TEXT_OF2: '📝 Texto "de" 2',
  TEXT_OF3: '📝 Texto "de" 3',
  TITLE: '📝 Título',
  TITLE1: '📝 Título 1',
  TITLE2: '📝 Título 2',
  TITLE3: '📝 Título 3',
} as const;

export type FieldType = keyof typeof field;

export default field;
