import IModule from '../interfaces/IModule';
import seals from '../enums/ESeals';
import { Complexity } from '../enums/EComplexity';
import ModuleImages from '../components/atoms/ModuleImages';

const modules: IModule[] = [
  {
    id: 1,
    image: ModuleImages[1] as string,
    name: 'Imagem Full',
    complexity: Complexity.LOW,
    description: 'A imagem tem largura fixa e altura variável. Pode ser usado para banner principais, reengajamento ou faixas.',
    seals: [seals.RECOMMENDED, seals.AGILE],
  },
  {
    id: 2,
    image: ModuleImages[2] as string,
    name: '2 Imagens Laterais',
    complexity: Complexity.LOW,
    description: 'Pode ser usado simulando 1 imagem com 2 links ou 2 imagens com 2 links.',
  },
  {
    id: 3,
    image: ModuleImages[3] as string,
    name: '4 Imagens Sequenciais',
    complexity: Complexity.MEDIUM,
    description: 'Até 4 imagens com até 4 links, todas com largura fixa e altura variável. Pode ser usado para simular uma imagem contínua com diferentes links ou diferentes imagens com diferentes links.',
    seals: [seals.VERSATILE],
  },
  {
    id: 4,
    image: ModuleImages[4] as string,
    name: '2 Imagens',
    complexity: Complexity.LOW,
    description: '2 links, um para cada imagem. As imagens têm largura fixa e altura livre.',
    seals: [seals.WIDELY_USED, seals.AGILE],
  },
  {
    id: 5,
    image: ModuleImages[5] as string,
    name: '3 Imagens',
    complexity: Complexity.LOW,
    description: '3 links, um para cada imagem. As imagens têm largura fixa e altura livre.',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 6,
    image: ModuleImages[6] as string,
    name: '4 Imagens',
    complexity: Complexity.LOW,
    description: '4 links, um para cada imagem. As imagens têm largura fixa e altura livre.',
  },
  {
    id: 7,
    image: ModuleImages[7] as string,
    name: '5 Imagens',
    complexity: Complexity.MEDIUM,
    description: '5 links, um para cada imagem. As imagens têm largura fixa e altura livre.',
  },
  {
    id: 8,
    image: ModuleImages[8] as string,
    name: 'Mosaico 4 Imagens',
    complexity: Complexity.LOW,
    description: '4 links, um para cada imagem. As imagens têm largura fixa e altura livre.',
    seals: [seals.SURPRISE],
  },
  {
    id: 9,
    image: ModuleImages[9] as string,
    name: 'Título secundário',
    complexity: Complexity.LOW,
    description: 'Pode ser utilizado antes de diferentes módulos como título de uma seção específica do e-mail. ',
    seals: [seals.RECOMMENDED],
  },
  {
    id: 10,
    image: ModuleImages[10] as string,
    name: 'Texto 1 coluna sem fundo',
    complexity: Complexity.MEDIUM,
    description: 'Fundo sempre branco.',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 11,
    image: ModuleImages[11] as string,
    name: 'Texto 1 coluna (fundo em cor)',
    complexity: Complexity.MEDIUM,
    description: 'Cor do fundo pode ter 3 opções de cor.1 será padrão + 2 alternativas.',
    seals: [seals.VERSATILE],
  },
  {
    id: 12,
    image: ModuleImages[12] as string,
    name: '2 Colunas de Texto',
    complexity: Complexity.MEDIUM,
    description: '2 links, um para cada coluna.',
    seals: [seals.CONTENT],
  },
  {
    id: 13,
    image: ModuleImages[13] as string,
    name: 'Texto com 2 colunas',
    complexity: Complexity.MEDIUM,
    description: '1 link para ambas as colunas.',
  },
  {
    id: 14,
    image: ModuleImages[14] as string,
    name: '3 Colunas de Texto',
    complexity: Complexity.MEDIUM,
    description: '3 links, um para cada coluna.',
  },
  {
    id: 15,
    image: ModuleImages[15] as string,
    name: 'Texto com 3 colunas',
    complexity: Complexity.MEDIUM,
    description: '1 link para todas as colunas.',
  },
  {
    id: 16,
    image: ModuleImages[16] as string,
    name: 'Imagem de Fundo + Texto Simples',
    complexity: Complexity.MEDIUM,
    description: 'A imagem vai como fundo do módulo e os textos são editáveis. * Este módulo tem suporte apenas parcial em alguns serviços de e - mail como o Windows Mail.Contudo, funciona normalmente nos principais serviços como Apple Mail, Outlook.com, Gmail e seus respectivos aplicativos Mobile.',
    seals: [seals.AGILE],
  },
  {
    id: 17,
    image: ModuleImages[17] as string,
    name: 'Imagem de Fundo + Texto Completo.',
    complexity: Complexity.HIGH,
    description: 'A imagem vai como fundo do módulo e os textos são editáveis. * Este módulo tem suporte apenas parcial em alguns serviços de e - mail como o Windows Mail.Contudo, funciona normalmente nos principais serviços como Apple Mail, Outlook.com, Gmail e seus respectivos aplicativos Mobile.',
    seals: [seals.AGILE],
  },
  {
    id: 18,
    image: ModuleImages[18] as string,
    name: 'Texto e Imagem à Esquerda',
    complexity: Complexity.MEDIUM,
    description: '',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 19,
    image: ModuleImages[19] as string,
    name: 'Texto e Imagem à Direita',
    complexity: Complexity.MEDIUM,
    description: '',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 20,
    image: ModuleImages[20] as string,
    name: 'Texto e 2 Imagens à Esquerda',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 21,
    image: ModuleImages[21] as string,
    name: 'Texto e 2 Imagens à Direita',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 22,
    image: ModuleImages[22] as string,
    name: '2 Colunas de Texto e Imagem',
    complexity: Complexity.MEDIUM,
    description: '2 links, um para cada coluna.',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 23,
    image: ModuleImages[23] as string,
    name: 'Texto e Imagem em 2 Colunas',
    complexity: Complexity.MEDIUM,
    description: '1 link para ambas as colunas',
  },
  {
    id: 24,
    image: ModuleImages[24] as string,
    name: '3 Colunas de Texto e Imagem',
    complexity: Complexity.HIGH,
    description: '3 links, um para cada coluna.',
    seals: [seals.CONTENT],
  },
  {
    id: 25,
    image: ModuleImages[25] as string,
    name: 'Itens em 4 colunas.',
    complexity: Complexity.HIGH,
    description: 'Até 4 vantagens e/ou benefícios.',
  },
  {
    id: 26,
    image: ModuleImages[26] as string,
    name: 'Itens com 3 imagens',
    complexity: Complexity.MEDIUM,
    description: 'Até 3 itens.',
  },
  {
    id: 27,
    image: ModuleImages[27] as string,
    name: 'Itens com 4 imagens',
    complexity: Complexity.HIGH,
    description: 'Até 4 itens',
    seals: [seals.VERSATILE],
  },
  {
    id: 28,
    image: ModuleImages[28] as string,
    name: 'Depoimento',
    complexity: Complexity.LOW,
    description: 'Até 8 itens.',
  },
  {
    id: 29,
    image: ModuleImages[29] as string,
    name: 'Itens em Lista',
    complexity: Complexity.MEDIUM,
    description: 'Cor do fundo pode ter 3 opções de cor. 1 será padrão + 2 alternativas.',
  },
  {
    id: 30,
    image: ModuleImages[30] as string,
    name: 'Faixa Ícone + Texto A',
    complexity: Complexity.MEDIUM,
    description: 'Cor do fundo pode ter 3 opções de cor. 1 será padrão + 2 alternativas.',
    seals: [seals.AGILE],
  },
  {
    id: 31,
    image: ModuleImages[31] as string,
    name: 'Faixa Ícone + Texto B',
    complexity: Complexity.MEDIUM,
    description: 'Cor do fundo pode ter 3 opções de cor. 1 será padrão + 2 alternativas.',
    seals: [seals.AGILE],
  },
  {
    id: 32,
    image: ModuleImages[32] as string,
    name: 'Faixa Cupom',
    complexity: Complexity.MEDIUM,
    description: 'Vitrine em 1 linha.',
    seals: [seals.AGILE],
  },
  {
    id: 33,
    image: ModuleImages[33] as string,
    name: 'Vitrine Individual',
    complexity: Complexity.HIGH,
    description: 'Vitrine em 1 linha, com imagem do produto à direita.',
  },
  {
    id: 34,
    image: ModuleImages[34] as string,
    name: 'Vitrine Individual Invertida',
    complexity: Complexity.HIGH,
    description: '',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 35,
    image: ModuleImages[35] as string,
    name: 'Vitrine Individual Horizontal A',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 36,
    image: ModuleImages[36] as string,
    name: 'Vitrine Individual Horizontal B',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 37,
    image: ModuleImages[37] as string,
    name: 'Vitrine Dupla',
    complexity: Complexity.HIGH,
    description: '',
  },
  {
    id: 38,
    image: ModuleImages[38] as string,
    name: 'Vitrine Dupla Simples',
    complexity: Complexity.MEDIUM,
    description: '',
    seals: [seals.WIDELY_USED],
  },
  {
    id: 39,
    image: ModuleImages[39] as string,
    name: 'Vitrine Dupla Horizontal',
    complexity: Complexity.HIGH,
    description: '',
  },
  {
    id: 40,
    image: ModuleImages[40] as string,
    name: 'Vitrine Dupla Horizontal Simples',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 41,
    image: ModuleImages[41] as string,
    name: 'Vitrine Tripla',
    complexity: Complexity.HIGH,
    description: '',
  },
  {
    id: 42,
    image: ModuleImages[42] as string,
    name: 'Vitrine Tripla Simples',
    complexity: Complexity.MEDIUM,
    description: '',
  },
  {
    id: 43,
    image: ModuleImages[43] as string,
    name: 'Vitrine Quádrupla',
    complexity: Complexity.HIGH,
    description: '',
  },
  {
    id: 44,
    image: ModuleImages[44] as string,
    name: 'Vitrine Quádrupla Simples',
    complexity: Complexity.MEDIUM,
    description: '',
  },
];

export default modules;
